python controller.py --model hsmm --device cuda --config hsmm_Bear
python controller.py --model hsmm --device cuda --config hsmm_Book
python controller.py --model hsmm --device cuda --config hsmm_Bowl
python controller.py --model hsmm --device cuda --config hsmm_Cup
python controller.py --model hsmm --device cuda --config hsmm_Fork
python controller.py --model hsmm --device cuda --config hsmm_Knife
python controller.py --model hsmm --device cuda --config hsmm_LeftHand
python controller.py --model hsmm --device cuda --config hsmm_RightHand
python controller.py --model hsmm --device cuda --config hsmm_Spoon
python controller.py --model hsmm --device cuda --config hsmm_Toy
